### PR TITLE
Adds functionality to emit hub connection state events once changed

### PR DESCRIPTION
**Pull request by svsk417**
Hi! I have the requirement to observe the connection state. This is my solution. Maybe we can introduce it into the lib as well :)

### CODE REVIEW

**Comment by eduardscript** [comment]
@sefidgaran looks like it don't wan't anyone to contribute to this awesome and helpful project.

**Comment by sefidgaran** [comment]
> @sefidgaran looks like it don't wan't anyone to contribute to this awesome and helpful project.

Sorry for delay, I will review this PR after update changelog, versions with description, all contributions are welcomed.

**Comment by sefidgaran** [comment]
> @sefidgaran looks like it don't wan't anyone to contribute to this awesome and helpful project.

Sorry for delay, I will review this PR after update changelog with description, all contributions are welcomed.

**Comment by brim-borium** [comment]
@sefidgaran I updated the changelog :)

**Review by sefidgaran — APPROVED** [review]

**Pull request merged**
